# GitHub Labels Configuration
# Synced automatically by .github/workflows/labels.yml using EndBug/label-sync
# Manual: gh label create "name" --description "desc" --color "color"

# Issue Types
- name: "type:bug"
  description: "Something isn't working"
  color: "D73A4A"

- name: "type:feature"
  description: "New feature request"
  color: "0E8A16"

- name: "type:docs"
  description: "Documentation improvements"
  color: "FEF2C0"

- name: "type:chore"
  description: "Maintenance, refactoring, dependencies"
  color: "BFD4F2"

- name: "type:question"
  description: "Further information is requested"
  color: "D876E3"

- name: "type:test"
  description: "Test improvements or additions"
  color: "1D76DB"

- name: "type:performance"
  description: "Performance improvements or optimization"
  color: "5319E7"

# Priority
- name: "priority:critical"
  description: "Critical - blocks release"
  color: "B60205"

- name: "priority:high"
  description: "High priority"
  color: "D93F0B"

- name: "priority:medium"
  description: "Normal priority"
  color: "FBCA04"

- name: "priority:low"
  description: "Low priority - nice to have"
  color: "0E8A16"

# Status
- name: "status:blocked"
  description: "Blocked by external dependency"
  color: "B60205"

- name: "status:needs-design"
  description: "Needs design decision before implementation"
  color: "FBCA04"

- name: "status:needs-info"
  description: "Needs more information from reporter"
  color: "FBCA04"

- name: "status:wontfix"
  description: "Will not be fixed"
  color: "FFFFFF"

- name: "status:duplicate"
  description: "Duplicate of another issue"
  color: "CFD3D7"

- name: "status:in-progress"
  description: "Currently being worked on"
  color: "1D76DB"

- name: "status:ready-for-review"
  description: "Ready for code review"
  color: "6F42C1"

# Areas
- name: "area:powershell"
  description: "PowerShell scripts and module"
  color: "7057FF"

- name: "area:action"
  description: "GitHub Action definition (action.yml)"
  color: "7057FF"

- name: "area:ci"
  description: "CI/CD pipeline and automation"
  color: "7057FF"

# Special
- name: "good first issue"
  description: "Good for newcomers"
  color: "7057FF"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "breaking change"
  description: "Introduces breaking changes"
  color: "B60205"

- name: "security"
  description: "Security-related issue"
  color: "D73A4A"

# Dependabot
- name: "deps:all"
  description: "Pull requests that update a dependency file"
  color: "0366D6"

- name: "deps:github-actions"
  description: "GitHub Actions workflow updates"
  color: "2088FF"

- name: "deps:powershell"
  description: "PowerShell module dependency updates"
  color: "012456"

- name: "deps:major"
  description: "Major version update requiring manual review"
  color: "D73A4A"

# Automated
- name: "status:needs-review"
  description: "PR needs manual review before merging"
  color: "FBCA04"

- name: "status:health-check-failure"
  description: "Automated issue from failed scheduled health check"
  color: "D73A4A"

- name: "status:stale"
  description: "Issue or PR has been inactive"
  color: "CFD3D7"

- name: "automerge"
  description: "Automatically merge when checks pass"
  color: "0E8A16"

- name: "do-not-merge"
  description: "Do not merge this PR"
  color: "B60205"
