name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "priority:medium"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below to help us investigate.

        **Before submitting**, please review the [README](https://github.com/marcus-hooper/send-teams-notification#readme) for usage guidance.

        **Tip**: Enable debug logging by adding `ACTIONS_STEP_DEBUG: true` to your repository secrets or workflow env. This provides more detailed output in the logs.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure workflow with...
        2. Trigger the action...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: |
        Describe what happened:
        - Did the notification send but look wrong?
        - Did it fail with an error?
        - Was the card missing expected content?
    validations:
      required: true

  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: Paste your workflow YAML here (redact secrets but include the full job/step configuration)
      render: yaml
      placeholder: |
        - name: Notify Teams
          uses: marcus-hooper/send-teams-notification@v1
          with:
            webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
            job_status: ${{ job.status }}
    validations:
      required: true

  - type: dropdown
    id: runner-os
    attributes:
      label: Runner OS
      description: Which runner are you using?
      options:
        - ubuntu-latest
        - ubuntu-24.04
        - ubuntu-22.04
        - ubuntu-slim
        - ubuntu-24.04-slim
        - ubuntu-24.04-arm
        - ubuntu-22.04-arm
        - windows-latest
        - windows-2025
        - windows-2022
        - windows-11-arm
        - macos-latest
        - macos-15
        - macos-15-intel
        - macos-14
        - macos-13
        - Self-hosted (specify in additional context)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: action-version
    attributes:
      label: Action Version
      description: The version of the action you are using
      placeholder: "@main, @v1, etc."
    validations:
      required: true

  - type: input
    id: powershell-version
    attributes:
      label: PowerShell Version
      description: The PowerShell version shown in the workflow logs (if known)
      placeholder: "7.4.6"
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: The exact error message (if any), including stack traces
      render: shell
      placeholder: |
        Invoke-RestMethod: The remote server returned an error: (400) Bad Request.
        At D:\a\repo\send-teams.ps1:42 char:5
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs here (redact sensitive info)
      render: shell
      placeholder: Expand the "Send Teams Notification" step and copy relevant output
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have [searched existing issues](https://github.com/marcus-hooper/send-teams-notification/issues?q=is%3Aissue) for duplicates
          required: true
        - label: I have verified the webhook URL works (e.g., tested with curl/Invoke-RestMethod or it previously worked with this action)
          required: true
        - label: Teams channel allows incoming webhooks (connector is not disabled by admin)
        - label: Webhook URL is for the correct channel

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
