name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

        **Before submitting**, please [search existing issues](../../issues?q=is%3Aissue+label%3Atype%3Afeature) to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Send Teams Notification does this affect?
      multiple: true
      options:
        - Adaptive Card content / formatting
        - Teams webhook integration
        - Action inputs / outputs
        - Status handling
        - Error handling / logging
        - Performance
        - Documentation
        - CI / Workflows
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information (examples, screenshots, links)
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
